---
- name: Create user '{{ user_name }}'
  user:
    name: "{{ user_name }}"
    password: "{{ user_password }}"
    shell: /bin/bash
    state: present

- name: Ensure .ssh directory exists for user
  file:
    path: "/home/{{ user_name }}/.ssh"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory
    mode: '0700'

- name: Generate Ed25519 SSH key pair
  openssh_keypair:
    path: "/home/{{ user_name }}/.ssh/id_ed25519"
    type: ed25519
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0600'
  register: ssh_keypair

- name: Display generated public key
  debug:
    var: ssh_keypair.public_key

- name: Check if user_cron_email is defined
  debug:
    msg: "The variable 'user_cron_email' is not defined, skipping cron email notification task."
  when: user_cron_email is not defined

- block:
  - name: Configure cron PATH
    cron:
      name: PATH
      user: "{{ user_name }}"
      env: yes
      job: "/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin"

  - name: Enable cron e-mail notifications for "{{ user_name }}"
    cron:
      name: MAILTO
      user: "{{ user_name }}"
      env: yes
      job: "{{ user_cron_email }}"
  when: user_cron_email is defined