---
- name: Set-up Ledger data files
  hosts: all
  become: true

  vars:
    - cronjob_fetch_prices: true

  pre_tasks:
    - name: Ensure all required variables are set
      fail:
        msg: "One or more required variables are missing: '{{ item }}'."
      loop:
        - git_user
        - git_password
      when: vars[item] is not defined

  tasks:
    - name: Ensure /Ledger directory exists
      file:
        path: "/Ledger"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        state: directory

    - block:
      - name: Git clone Ledger
        git:
          repo: "{{ ledger_repo }}"
          dest: "/Ledger"
          update: no

      - name: Set global Git user name
        git_config:
          name: user.name
          value: "{{ git_user }}"
          scope: global

      - name: Set global Git user email
        git_config:
          name: user.email
          value: "{{ git_password }}"
          scope: global

      - name: Git clone custom ledger-importers
        git:
          repo: "https://github.com/kstockk/ledger-importers"
          dest: "/Ledger/importers"
          update: yes

      - name: Set LEDGER_DATA_DIR environment variable in .bashrc
        lineinfile:
          path: /home/{{ user_name }}/.bashrc
          line: 'export LEDGER_DATA_DIR="/Ledger"'
          state: present
          create: yes
      become_user: "{{ user_name }}"

    - name: Create symlink for /Ledger/data/inbox pointing to "{{ mount_point }}"/data/inbox
      file:
        src: "{{ mount_point }}/data/inbox"
        dest: /Ledger/data/inbox
        state: link

    - name: Create symlink for /data/documents pointing to "{{ mount_point }}"/data/documents
      file:
        src: "{{ mount_point }}/data/documents"
        dest: /Ledger/data/documents
        state: link

    - name: Restart Fava service
      systemd:
        name: fava.service
        state: restarted

    - name: Check if prices.beancount exists
      stat:
        path: "/Ledger/data/prices.beancount"
      register: prices_file
      when: cronjob_fetch_prices | default(False)

    - name: Create cron job at 20:00 daily to fetch new beancount prices
      ansible.builtin.cron:
        name: "Fetch Beancount Prices"
        user: "{{ user_name }}"
        minute: "0"
        hour: "20"
        job: "/opt/fava_env/bin/bean-price --update /Ledger/data/master.beancount >> /Ledger/data/prices.beancount"
      when: 
        - cronjob_fetch_prices | default(False)
        - prices_file.stat.exists
